Closes #59
Kode-Brew/Kode-Brew pull request #100
Opened 2024-07-01 15:24 UTC by bearanha

- Completa back e front de Show de tasks.

2024-07-01 21:39 UTC, BernardoNal requested changes

2024-07-01 21:39 UTC, BernardoNal commented on app/assets/stylesheets/config/_colors.scss
> +$light-green: rgba(34, 168, 34, 0.5);
Analisar os lugares que usam essa cor

2024-07-03 22:01 UTC, BernardoNal approved these changes

2024-07-04 20:37 UTC, thony-vieira approved these changes

2024-07-04 20:37 UTC, merged