Feat/adjust crud user/#3
Kode-Brew/Kode-Brew pull request #15
Opened 2024-05-17 15:50 UTC by thony-vieira

Adaptação do User para comportar novos campos (role, points, name), view de edit e new user ajustadas. Para a página de cadastro de usuário é possível escolher uma ROLE para ele, eventualmente isso vai ser um privilégio de algum nível de administração, porém para testes, já está funcionando. Adequei as seeds para lidar com alguns problemas de validação e acrescentei novos campos para se adequarem, também criei novas migrations. Portanto, RAILS DB:MIGRATE DB:SEED.
As mudanças no gemfile, foram feitas pelo rubocop. Não vai gerar problema algum.

2024-05-17 21:59 UTC, BernardoNal requested changes
E você esqueceu de colocar os models refentes a user com "has_many : project_members"

2024-05-17 21:59 UTC, BernardoNal commented on db/seeds.rb
> +  { sprint_id: Sprint.first.id, lecture_id: Lecture.first.id, project_member_id: ProjectMember.first.id },
Faz alguma diferença? pois esse campo nos permitimos ser nulo

2024-05-17 21:59 UTC, BernardoNal commented on db/seeds.rb
> +  { email: 'john@example.com', password: 'password123', password_confirmation: 'password123', name: 'John Smith', role: 'TA', points: '0' },
ele obriga esse password_confirmation? caso contrário não há necessidade

2024-05-17 21:59 UTC, BernardoNal commented on db/migrate/20240517134315_add_points_to_users.rb
os 3 migrates podem ser um só , segue o exemplo
![image](https://github.com/Kode-Brew/Kode-Brew/assets/50677768/0edef385-daaa-4262-95f0-097d70f2eb90)

2024-05-17 22:08 UTC, thony-vieira commented on db/seeds.rb
> +  { email: 'john@example.com', password: 'password123', password_confirmation: 'password123', name: 'John Smith', role: 'TA', points: '0' },
Para editar usuário pelo devise , ele precisa da confirmação de password.

2024-05-17 22:11 UTC, thony-vieira commented on db/seeds.rb
> +  { sprint_id: Sprint.first.id, lecture_id: Lecture.first.id, project_member_id: ProjectMember.first.id },
Essa é a linha exata que tá impedindo o código de quebrar na hora de rodar as seeds, pois a sprint lecture estava requerendo um project_member para ser criada, o que faz sentido.

2024-05-17 22:30 UTC, thony-vieira commented on db/migrate/20240517134315_add_points_to_users.rb
Valeu, tinha esquecido disso.

2024-05-17 23:37 UTC, BernardoNal requested changes

2024-05-17 23:37 UTC, BernardoNal commented on app/models/user.rb
> +  has_many :project_members
Falto has_many de sprint_lectures e de ticket( nesse coloque um comentario no codigo que faz referencias ao ticktes como professor)

2024-05-20 19:15 UTC, BernardoNal approved these changes

2024-05-20 19:18 UTC, bearanha approved these changes

2024-05-20 19:57 UTC, merged