Feat/#142
Kode-Brew/Kode-Brew pull request #157
Opened 2024-07-20 10:04 UTC by perrigii

- Refinamento da sidebar;
- Adição de javascript para abrir e fechar o menu;
- Correção da rota de show de um projeto atual;
- Correção do form de new_project.

2024-07-20 14:13 UTC, BernardoNal requested changes

2024-07-20 14:13 UTC, BernardoNal commented on app/javascript/sidebar.js
> +const hamBurger = document.querySelector(".toggle");
hamburguer, acredito que possa ter nome melhor para essa variável

2024-07-20 14:13 UTC, BernardoNal commented on app/views/shared/_sidebar.html.erb
> +          <% if @project %>
@project vai funcionar sempre?

2024-07-20 20:42 UTC, BernardoNal approved these changes

2024-07-21 15:13 UTC, CaioBrasetti approved these changes

2024-07-21 15:13 UTC, merged