Feat/barra de progresso da tela de dashboard/#36
Kode-Brew/Kode-Brew pull request #66
Opened 2024-06-11 21:25 UTC by thony-vieira

Implementação do componente de barra de progresso.
A barra possui comportamento dinâmico, tendo seu comportamento alterado pelo campo recém criado de active_sprint(model de project), bem como a quantidade de sprints que o projeto terá.

2024-06-12 15:12 UTC, CaioBrasetti approved these changes

2024-06-12 18:30 UTC, BernardoNal requested changes

2024-06-12 18:30 UTC, BernardoNal commented on app/assets/stylesheets/components/_progress_bar.scss
> +$brand-primary: #008100;
Já temos um arquivo que salvamos as variáveis de cor , jogar essas cores para esse arquivo(_colors.scss) e modificar  os nomes que forem iguais

2024-06-13 17:06 UTC, thony-vieira commented on app/assets/stylesheets/components/_progress_bar.scss
> +$brand-primary: #008100;
Vou providenciar.

2024-06-13 21:45 UTC, BernardoNal approved these changes

2024-06-13 21:46 UTC, merged